project:
  type: website
  output-dir: docs
  resources: googlef06d37c17cf410a9.html

website:
  title: "GravelRrr"
  description: "Not just another bike geometry comparison tool"
  site-url: https://bikegeometry.site
  navbar:
    background: primary
    search: true
    right:
      - text: "About"
        file: about.qmd
    left:
      - text: "Gravel Plots"
        menu:
          - qmd/gravel_histo.qmd
          - qmd/gravel_scatter.qmd
          - qmd/gravel_ternary.qmd
      - text: "Gravel Style"
        menu:
          - qmd/what_is_a_gravel_bike.qmd
          - qmd/gravel_tree.qmd
          - qmd/gravel_class.qmd
      - text: "Gravel Stories"
        menu:
          - qmd/which_gravel_bikes_are_mtb_inspired.qmd
          - qmd/mtb_90s.qmd
      - text: "New Bike Day"
        menu:
          - qmd/nbd/revoltx.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: source

